blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import (
    BlogCreateView,
    BlogListView,
    BlogDetailView,
    BlogUpdateView,
    BlogDeleteView,
)


app_name = BlogConfig.name

urlpatterns = [
    path("create/", BlogCreateView.as_view(), name="create"),
    path("blog_list/", BlogListView.as_view(), name="list"),
    path("view/<int:pk>/", BlogDetailView.as_view(), name="view"),
    path("update/<int:pk>/", BlogUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", BlogDeleteView.as_view(), name="delete"),
]

catalog/urls.py
from django.urls import path

from catalog.apps import CatalogConfig
from catalog.views import ProductListView, ProductDetailView, ContactsPageView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView

app_name = CatalogConfig.name

urlpatterns = [
    path("", ProductListView.as_view(), name="catalog_list"),
    path("contacts/", ContactsPageView.as_view(), name="contacts"),
    path("catalog/<int:pk>/", ProductDetailView.as_view(), name="catalog_detail"),
    path('create/', ProductCreateView.as_view(), name="create_product"),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name="product_update"),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name="product_delete"),
]

config/urls.py
"""
Конфигурация URL для проекта конфигурации.

Список `urlpatterns` направляет URL к представлениям. Для получения дополнительной информации см.:
    https://docs.djangoproject.com/en/5.1/topics/http/urls/

Примеры:
Виды функций
1. Добавьте импорт: from my_app import views
2. Добавьте URL в urlpatterns: path('', views.home, name='home')
Виды на основе классов
1. Добавьте импорт: from other_app.views import Home
2. Добавьте URL в urlpatterns: path('', Home.as_view(), name='home')
Включение другого URLconf
1. Импортируйте функцию include(): from django.urls import include, path
2. Добавьте URL в urlpatterns: path('blog/', include('blog.urls'))
"""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="login")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from blog.utils import upload_to


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name="название")
    body = models.TextField(verbose_name="содержимое")
    image = models.ImageField(
        upload_to=upload_to,
        blank=True,
        null=True,
        verbose_name="Изображение",
        help_text="Загрузите изображение",
    )
    created_at = models.DateField(
        blank=True, null=True, verbose_name="Дата создания записи"
    )
    # updated_at = models.DateField(
    #     blank=True, null=True, verbose_name="Дата изменения записи"
    # )
    views_count = models.IntegerField(default=0, verbose_name="Просмотров")
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    slug = models.CharField(max_length=150, verbose_name='slug', null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "статья"
        verbose_name_plural = "статьи"

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    CreateView,
    ListView,
    DetailView,
    UpdateView,
    DeleteView,
)
from pytils.templatetags.pytils_translit import slugify

from blog.models import Blog


# Create your views here.
class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    fields = ("title", "body", "created_at", 'image')
    success_url = reverse_lazy("blog:list")

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)


class BlogListView(LoginRequiredMixin, ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(LoginRequiredMixin, DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ("title", "body", "image", "is_published")
    success_url = reverse_lazy("blog:list")

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy("blog:list")

blog/templates/blog/blog_confirm_delete.html
{{% extends 'catalog/base.html' %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row">
            <div class="col-4">
                <form class="row" method="post" enctype="multipart/form-data">
                    <div class="card shadow-sm">
                        <p class="card-text">Вы уверены, что хотите удалить карточку? {{ object.name }}</p>
                        <div class="card-body">
                            {% csrf_token %}
                        </div>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button type="submit" class="btn btn-primary">Удалить</button>
                                <a class="btn btn-primary" href="{% url 'catalog:catalog_list' %}" role="button">Отмена</a>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <div class="col">
                <div class="card shadow-sm">
                    <img src="/media/{{ object.image }}"/>
                    <div class="card-body">
                        <p class="card-text">Название: {{ object.title }}</p>
                        <p class="card-text">Содержимое: {{ object.body }}</p>
                        <p class="card-text">Дата создания записи: {{ object.created_at }}</p>
                        <p class="card-text">Просмотров: {{ object.views_count }}</p>
                        <p class="card-text">Опубликовано: {{ object.is_published }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'blog:update' blog.pk %}" role="button">Изменить</a>
                                <a class="btn btn-primary" href="{% url 'blog:delete' blog.pk %}" role="button">Удалить</a>
                                <a class="btn btn-primary" href="{% url 'catalog:catalog_list' %}" role="button">Вернуться к каталогу</a>
                            </div>
                            <small class="text-body-secondary"></small>
                        </div>
                        <div class="card-footer">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row">
            <div class="col-4">
                <form class="row" method="post" enctype="multipart/form-data">
                    <div class="card shadow-sm">
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                        </div>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button type="submit" class="btn btn-primary">
                                    {% if object %}
                                    Сохранить
                                    {% else %}
                                    Создать карточку
                                    {% endif %}
                                </button>
                                <a class="btn btn-primary" href="{% url 'catalog:catalog_list' %}" role="button">Вернуться
                                    к каталогу</a>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for blog in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <img class="card-img-top" src="{{ blog.image | media_filter }}">
                    <div class="card-body">
                        <p class="card-text">Название: {{ blog.title }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'blog:view' blog.pk %}"
                                   role="button">Просмотр</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}